55 from zarr
TUDelftGeodesy/sarxarray pull request #56
Opened 2024-10-01 14:12 UTC by rogerkuou

Fix #55.

- [ ] Add `from_zarr` function
- [ ] Add test files and unit tests

2024-10-01 14:44 UTC, rogerkuou commented
Hi @SarahAlidoost, when you have time, can you review this PR? The details should be in the issue description.

While creating this PR, the ruff linting is failling on the notebooks. These notebooks exists mainly for archiving purposes. In the future they will all be moved to [PyDePSI workflow](https://github.com/MotionbyLearning/PyDePSI/tree/main/examples). Therefore I turned off ruff linting on them. I also replaced the unit test for linting with a pre-commit hook.

2024-10-02 10:46 UTC, SarahAlidoost commented on sarxarray/_io.py
> +    """Read a SLC stack or relabted variables from zarr files.
```suggestion
    """Read a SLC stack or related variables from zarr files.
```

2024-10-02 10:48 UTC, SarahAlidoost commented on sarxarray/_io.py
> +    """Read a SLC stack or relabted variables from zarr files.
It is not clear what "or related variables" means. This function does not support selecting only one variable to read from a zarr file, right? I suggest removing "or related variables".

2024-10-02 10:57 UTC, SarahAlidoost commented on sarxarray/_io.py
> +        Paths to the zarr files.
Why is this plural i.e. `files` and `paths`? below `xr.open_zarr` is used to open a zarr file, and only works with one path and not for example a string glob, right? I suggest replacing the variable name `files_zarr` with `file_zarr` or just `path`.

2024-10-02 10:58 UTC, SarahAlidoost commented on sarxarray/_io.py
> +    if not all([dim in ds.dims for dim in ["azimuth", "range", "time"]]):
```suggestion
    if any([dim not in ds.dims for dim in ["azimuth", "range", "time"]]):
```

2024-10-02 10:58 UTC, SarahAlidoost commented on sarxarray/_io.py
> +    if not all([var in ds.variables for var in ["real", "imag"]]):
```suggestion
    if any([var not in ds.variables for var in ["real", "imag"]]):
```

2024-10-02 11:13 UTC, SarahAlidoost commented on sarxarray/_io.py
> +def from_zarr(files_zarr: str | Path) -> xr.Dataset:
The `from_zarr` function currently wraps the [`xarray.open_zarr`](https://docs.xarray.dev/en/latest/generated/xarray.open_zarr.html) function but does not expose its additional arguments, which restricts users' flexibility when using `from_zarr`. I suggest adding `**kwargs` to allow users to specify other arguments for `open_zarr`, or at least, expose some commonly used parameters e.g. `chunks`, `drop_variables`, and `zarr_version`, ....

2024-10-02 11:16 UTC, SarahAlidoost commented on tests/test_io.py
> +        assert all([dim in slcs.dims for dim in ["azimuth", "range", "time"]])
```suggestion
        assert all(dim in slcs.dims for dim in ["azimuth", "range", "time"])
```

2024-10-02 11:16 UTC, SarahAlidoost commented on tests/test_io.py
> +        assert all([var not in slcs.variables.keys() for var in ["real", "imag"]])
```suggestion
        assert all(var not in slcs.variables.keys() for var in ["real", "imag"])
```

2024-10-02 11:16 UTC, SarahAlidoost commented on tests/test_io.py
> +            [var in slcs.variables.keys() for var in ["complex", "amplitude", "phase"]]
```suggestion
            [var in slcs.variables.keys() for var in ["complex", "amplitude", "phase"]]
```
```suggestion
            var in slcs.variables.keys() for var in ["complex", "amplitude", "phase"]
```

2024-10-02 11:20 UTC, SarahAlidoost requested changes
@rogerkuou please see my comments and suggestions, the main concern is [this comment](https://github.com/TUDelftGeodesy/sarxarray/pull/56/files#r1784319729).

2024-10-11 09:34 UTC, rogerkuou commented
Thanks @SarahAlidoost! I adpted your suggestions and re-write `from_zarr` to `from_ds`. Now the reading function operates on a DS read by `open_zarr`. Can you give it another look?

2024-10-11 15:15 UTC, SarahAlidoost approved these changes
@rogerkuou thanks for the fixes, looks great :+1:

2024-10-14 07:19 UTC, merged