Joss paper
TUDelftGeodesy/sarxarray pull request #62
Opened 2024-12-16 10:28 UTC by rogerkuou

Joss paper

2024-12-16 12:58 UTC, rogerkuou commented
Hi @SarahAlidoost and @FreekvanLeijen, I drafted a JOSS paper according to [this guideline](https://joss.readthedocs.io/en/latest/paper.html). I put both of you as authors of this paper since you both have significant contribution in the concept and implementation.

When you have time, can you review this draft? You can find a rendered paper in the [artifact of the github workflow](https://github.com/TUDelftGeodesy/sarxarray/actions/runs/12350756258/artifacts/2325334191).

2025-01-06 13:04 UTC, SarahAlidoost commented on paper/paper.md
> +Satellite-based Synthetic Aperture Radar (SAR) provides invaluable image data for Earth Observation. The Interferometric SAR (InSAR) technique, which leverages a stack of SAR images in Single Look Co
```suggestion
Satellite-based Synthetic Aperture Radar (SAR) provides invaluable image data for Earth observation. The Interferometric SAR (InSAR) technique, which utilizes a stack of SAR images in Single Look Complex (SLC) format, plays a significant role in various surface motion monitoring applications, e.g. civil-infrastructure stability [@chang2014detection; @chang2017railway], and hydrocarbons extraction [@fokker2016application; @ZHANG2022102847]. To facilitate advanced data processing for InSAR communities, we developed `SARXarray`, a Xarray extension for handling SLC SAR stacks. 
```

2025-01-06 13:12 UTC, SarahAlidoost commented on paper/paper.md
> +Satellite-based SAR generates data stacks with long temporal coverage, broad spatial coverage and high spatio-temporal resolution. [@moreira2013tutorial] Handling it in an efficient way is a common c
```suggestion
Satellite-based SAR generates data stacks with long temporal coverage, broad spatial coverage, and high spatio-temporal resolution. [@moreira2013tutorial] Handling SAR data stacks in an efficient way is a common challenge within InSAR communities. To address this challenge, High-Performance Computing (HPC) is often used to process data in a parallel and distributed manner. However, to fully leverage HPC capabilities, data processing workflows need to be customized for each specific use-case.
```

2025-01-06 13:18 UTC, SarahAlidoost commented on paper/paper.md
> +Aiming to meet the need for efficient processing of SLC SAR stacks with minimum effort on code customization, we developed `SARXarray` for SLC SAR stack processing.
```suggestion
To facilitate efficient processing of SLC SAR stacks and minimize code customization, we developed `SARXarray` for SLC SAR stack. 
```

2025-01-06 13:27 UTC, SarahAlidoost commented on paper/paper.md
> +`SARXarray` is developed based on two established Python libraries `Xarray` and `Dask` from the [Pangeo community](https://www.pangeo.io/). Implemented as an Xarray extension, it utilizes Xarray’s su
```suggestion
`SARXarray` leverages two well-established Python libraries `Xarray` and `Dask` from the [Pangeo community](https://www.pangeo.io/). It utilizes Xarray’s support on labeled multi-dimensional datasets to stress the space-time character of an SLC SAR stack. `Dask` is used to perform lazy evaluation of operations and block-wise computations. SARXarray can be integrated into existing Python workflows of InSAR processing and deployed on a variety of computational infrastructures. 
```

2025-01-06 13:28 UTC, SarahAlidoost commented on paper/paper.md
> +We provide a tutorial as a Jupyter notebook to demonstrate the basic functionalities of `SARXarray`:
```suggestion
We provided a tutorial as a Jupyter notebook to demonstrate the functionalities of `SARXarray`:
```

2025-01-06 13:29 UTC, SarahAlidoost commented on paper/paper.md
> +The tutorial demonstrates the following steps:
```suggestion
The tutorial includes the following steps:
```

2025-01-06 13:30 UTC, SarahAlidoost commented on paper/paper.md
> +- Applying a simple SAR operation on the loaded stack
```suggestion
- Applying a SAR operation on the loaded stack
```

2025-01-06 13:31 UTC, SarahAlidoost commented on paper/paper.md
> +The authors express sincere gratitude to the Dutch Research Council (Nederlandse Organisatie voor Wetenschappelijk Onderzoek, NWO) for their generous funding of the `SARXarray` development through th
Regarding SURF acknowledgement, if the project has received a grant from SURF for using resources, the Acknowledgement text is mentioned in the grant agreement. Please use that text here.

2025-01-06 13:36 UTC, SarahAlidoost commented on paper/paper.md
> +- Applying a simple SAR operation on the loaded stack
can we also add an example of "complex_coherence" to the notebook?

2025-01-06 13:38 UTC, SarahAlidoost requested changes
@rogerkuou thanks for preparing the draft. I left some comments, please let me know if something is unclear.

2025-02-14 14:54 UTC, rogerkuou commented on paper/paper.md
> +The authors express sincere gratitude to the Dutch Research Council (Nederlandse Organisatie voor Wetenschappelijk Onderzoek, NWO) for their generous funding of the `SARXarray` development through th
Thanks @SarahAlidoost, I included the surf grant numbers here

2025-02-14 14:59 UTC, rogerkuou commented on paper/paper.md
> +- Applying a simple SAR operation on the loaded stack
Added coherence computation to the bulletpoint

2025-02-14 15:01 UTC, rogerkuou commented
Hi @SarahAlidoost, thanks for reviewing the JOSS paper and apoligies for only reacting till now. Can I adapted all your suggestions. Can you give another look?

2026-02-03 16:33 UTC, FreekvanLeijen requested changes
Hi Ou, nice story! I inserted some adaptions. Please have a look.

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> + - name: Delft University of Technology, Netherlands
```suggestion
 - name: Department of Geoscience and Remote Sensing, Delft University of Technology, Netherlands
```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> +Satellite-based SAR generates data stacks with long temporal coverage, broad spatial coverage, and high spatio-temporal resolution. [@moreira2013tutorial] Handling SAR data stacks in an efficient way
```suggestion
Satellite-based SAR generates data stacks with long temporal coverage, wide spatial coverage, and high spatio-temporal resolution [@moreira2013tutorial]. Handling SAR data stacks in an efficient way is a common challenge within the InSAR community. To address this challenge, High-Performance Computing (HPC) is often used to process data in a parallel and distributed manner. However, to fully leverage HPC capabilities, data processing workflows need to be customized for each specific use-case.
```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> +To facilitate efficient processing of SLC SAR stacks and minimize code customization, we developed `SARXarray` for SLC SAR stack.
```suggestion
To facilitate efficient processing of SLC SAR stacks and minimize code customization, we developed `SARXarray`. 
```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> +Satellite-based Synthetic Aperture Radar (SAR) provides invaluable image data for Earth observation. The Interferometric SAR (InSAR) technique, which utilizes a stack of SAR images in Single Look Com
```suggestion
Satellite-based Synthetic Aperture Radar (SAR) provides invaluable data for Earth Observation. The Interferometric SAR (InSAR) technique [@hanssen01], which utilizes a stack of SAR images in Single Look Complex (SLC) format, plays a significant role in various surface motion monitoring applications, e.g. civil-infrastructure stability [@chang2014detection; @chang2017railway;ozer2018applicability], and hydrocarbons extraction [@fokker2016application; @ZHANG2022102847]. To facilitate advanced data processing for InSAR communities, we developed `SARXarray`, a Xarray extension for handling SLC SAR stacks. 
```

I do not want to use the wording 'image data' in the first sentence, because image suggests an optical image. In the second sentence, we use 'SAR image', which I think is acceptable.

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.bib
> +
```suggestion
@article{ozer2018applicability,
  title={Applicability of satellite radar imaging to monitor the conditions of levees},
  author={{\"O}zer, I{\c{s}}{\i}l E and van Leijen, Freek J and Jonkman, Sebastiaan N and Hanssen, Ramon F},
  journal={Journal of Flood Risk Management},
  pages={e12509},
  year={2018},
  publisher={Wiley Online Library}
}

```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.bib
> +
```suggestion
@book{hanssen01,
    key     = {insar defo atmos delftsar rfh_book},
    author  = {R. F. Hanssen},
    title   = {Radar Interferometry: Data Interpretation and Error Analysis},
    year    = {2001},
    publisher = {Kluwer Academic Publishers},
    address = {Dordrecht},
    mailto  = {r.f.hanssen@tudelft.nl},
    available = {photocopy},
    doi = {10.1007/0-306-47633-9},
    ISBN = {978-0-7923-6945-5}
} 

```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> +We provided a tutorial as a Jupyter notebook to demonstrate the functionalities of `SARXarray`:
```suggestion
We provide a tutorial as a Jupyter notebook to demonstrate the functionalities of `SARXarray`:
```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> +  - Create Mean-Reflection-Map (MRM)
```suggestion
  - Creation of a Mean-Reflectivity-Map (MRM)
```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> +  - Calculate complex coherence
```suggestion
  - Calculation of coherence
```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> +The authors express sincere gratitude to the Dutch Research Council (Nederlandse Organisatie voor Wetenschappelijk Onderzoek, NWO) for their generous funding of the `SARXarray` development through th
```suggestion
The authors express sincere gratitude to the Dutch Research Council (Nederlandse Organisatie voor Wetenschappelijk Onderzoek, NWO) for their generous funding of the `SARXarray` development through the Collaboration in Innovative Technologies (CIT 2021) Call, grant NLESC.CIT.2021.006. Special thanks to SURF for providing valuable computational resources for `SARXarray` testing via grants EINF-2051, EINF-4287 and EINF-6883.
```

2026-02-03 16:33 UTC, FreekvanLeijen commented on paper/paper.md
> +We would also like to thank Dr. Francesco Nattino and Dr. Meiert Willem Grootes for the insightful discussions, which are important contributions to this work.
```suggestion
We would also like to thank Dr. Francesco Nattino and Dr. Meiert Willem Grootes of the Netherlands eScience Center for the insightful discussions, which are important contributions to this work.
```

2026-02-09 06:28 UTC, rogerkuou commented
Hi @FreekvanLeijen, I adapted all of your comments. Thanks for the review! Can you give a final look?

BTW I closed and reopened this PR for a correct rendering of the changed files.

2026-03-20 09:08 UTC, rogerkuou commented
Got an oral greenlight from @FreekvanLeijen to submit. Will merge now.

2026-03-20 09:08 UTC, merged